"""empty message

Revision ID: b2f3a0c1b664
Revises: dd280703c7fe
Create Date: 2020-06-25 23:04:28.899137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f3a0c1b664'
down_revision = 'dd280703c7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('face_image_location', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'face_image_location')
    op.drop_column('user', 'confirmed_at')
    # ### end Alembic commands ###
